project:
  type: website

website:
  title: ""
  site-url: https://h-escoffier.github.io
  description: "personal blog"

  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects/index.qmd
      - text: Reflect
        href: reflect/index.qmd
      - text: Art
        href: art/index.qmd
      - text: Advent of Code
        href: advent_of_code/index.qmd

format:
  html:
    theme: cosmo
    toc: true
    highlight-style: dracula 
    code-line-numbers: true
